### ISSUE TITLE
initial live example

### ISSUE THREAD

**Issue by rkdarst** [coderefinery/jupyter#11]
Add "calculation of pi" example as a different way of starting the lesson.

But #7 may be a better option in fact, since it's the same example.  Adapt that instead if possible.

- [ ] add sample notebook
- [ ] add instructor guide to explain how to build up the example and in what order.  (the idea is to not just make a final notebook to see, but build it up piece by piece and show how each step works and the reasoning)
- [ ] add other starting method to instructor guide.

**Comment by rkdarst** [comment]
OK, so... pi example shows building up from the start, which shows a different thing than looking at an existing project.... so something to consider.  I think the build up from zero is good.

Also, also, calculation of pi is NOT something that is generally interesting to people, which is against that.  Maybe a development of the zipf's law calculation from the start?

Thoughts?

**Comment by bast** [comment]
I liked the demo of building things up: idea, code, reasoning, debugging, result (plot) - initially I "feared" it would be too Python specific but it worked. Whatever example we use, it has to be as simple as possible. And it is nice if we perhaps relate to the word-count.

**Comment by rkdarst** [comment]
Yeah, I think I settled on the solution of rewriting this for the word
count example.  It would show the other way of doing the same thing with
things interleaved...

**Comment by wikfeldt** [comment]
word-count now added in 662dae3, closing issue
