### ISSUE TITLE
New intro: live dynamic example at the beginning.

### ISSUE THREAD

**Issue by rkdarst** [coderefinery/jupyter#13]
Related to #28, I felt that this lesson got a relatively slow start and because I was new, it carried over to most of the rest of it.  When I taught jupyter earlier, I had a different strategy which I'll suggest here.

First, here is my model notebook:
https://github.com/AaltoScienceIT/python-r-data-analysis-course/blob/master/02_Jupyter_demo_pi.ipynb

I started a new notebook and started telling a story:
* I am a researcher who wants to calculate pi.  I don't know what I am doing so begin at the beginning.
* Add a markdown cell at the top saying what I am doing.
* Import relevant things and add simple loop and stochastic calculation (pick random points, are the yin a circle or not?)
* Now I have to convert my statistics to pi.  I could do my derivations on paper and then enter the formula, but instead I enter a markdown cell and do the derivations directly there.
* Then, I implement the formula to calculate pi.
* Small discussion: when reporting my work to my advisor, this is a much more useful form!  They can review everything.
* Now, we want to extend our work.  Let's add a visualization.  Go back and record all of the points and make a matplotlib visualization of what falls in the circle.
* Then I go add add some line magics - %timeit for example.  Demonstrate these but we  will get back to more later.
* Discussions: notebook advantages and disadvantages.  When to use, when not to use.

I found that this was a dynamic and interesting story to begin with.  After this, lead in to the material here which explains how to actually use jupyter - the details.  The real examples can be immediately after this, or before.

As for presenting, it was fairly easy, but I did need to refer to the document to copy from - it's hard do do the derivations in real time with an audience!  A bit more advanced thought and planning is needed, too (you should probably go through it once before presenting).

**Comment by bast** [comment]
JOSS is a good idea but we need to keep it simple/simpler. The Zipf example is not easy to follow if you have never seen Python. I found Richard's example in Aalto simpler to follow and more convincing. Of course it's good if we keep a red line that goes through the workshop.

**Comment by wikfeldt** [comment]
we can switch to a simpler example than Zipf's law, but we could also stick with Zipf and start with really simple steps to analyze a word-count output file (included in the jupyter repo). The full analysis (comparing with 1/N law, adding a widget) can then be left as an exercise perhaps

**Comment by bast** [comment]
If we can go with Zipf, it is better than introducing a new example. But for me a simple convincing example is more important than compatibility with other lessons since the Jupyter lesson should also be consumable on its own. Also it is important for me to have a convincing example that does not require too much Python knowledge.

**Comment by rkdarst** [comment]
I think that in the end, the exact example doesn't matter too much - whoever does it and can make the best example.  Though integrating to the rest of the JOSS idea would be ideal.

In the example the code doesn't matter and we can say not to pay attention to it too much, but on the flip side having simple code will help to not pay attention to it.  I think zipf could be made as simple or simpler...

When designing an example, it should be simple but complex enough to have: text-based intro, deriving an equation and then using it in code, going back and editing code in a cycle, plot, and ideally add some widgets maybe.  It's a lot to plan...

Anyway, I can adapt my pi example and try to make something short term (of course, whatever we make is more of an instructor guide since it has to be seen live to make sense).  At least then there is something, and it's OK if it's replaced later.  Should I try to do this?

**Comment by bast** [comment]
I still really like the JOSS idea. Also sorry for not answering your question but I would like it to be less about "what we have done earlier as scripts we can also do as notebook, see?" (this is a bit how I felt watching the current Zipf example in Jupyter) and more of "Yes! For this notebooks really make sense! I need to remember that next time I want to test something out". Sorry that my answer is not more concrete. I think am not the right person to decide this since I have not contributed neither to this material much, nor to its teaching.

**Comment by wikfeldt** [comment]
@rkdarst i wouldn't mind having a quick go first at simplifying the initial word-count type-along. It sounds like starting the lesson with an empty notebook, and interactively add text, simple code and visualizations to it is the way to go. I think this can work well with the word-count project

**Comment by wikfeldt** [comment]
@rkdarst the lesson has now been completely revamped. Meant to add you as reviewer to the PR but accidentally self-merged #27 ... Anyways, care to have a look? The lesson starts with motivation and overview of the interface, but then goes directly into computing pi in a notebook (episode 3). See https://coderefinery.github.io/jupyter/

**Comment by rkdarst** [comment]
I'd say it looks good, as commented elsewhere.  Thanks for the revamp!
