### ISSUE TITLE
Pygments lexer name warnings during build

### ISSUE THREAD

**Issue by ruokolt** [coderefinery/jupyter#151]
*Problem* 

Multiple warnings received during build

> Pygments lexer name 'jupyter' is not known
> Pygments lexer name 'file' is not known

*Why does it matter*

Not known

*What is the cause*

Not known

*How to fix*

Not known

**Comment by bast** [comment]
It matters because if the lexer is not known, it will not highlight at all.

Cause: "jupyter" is not an existing highlighting language it seems.

How to fix: use "python" instead? But maybe it complains then as well about the magics?
