### ISSUE TITLE
Binder exercise: many participants struggled with pushing files to GitHub

### ISSUE THREAD

**Issue by bast** [coderefinery/jupyter#152]
We need explicit steps here and this seems not enough:

 "Create a new GitHub repository.

Commit and push the notebook which we have created earlier to this repository"

**Comment by MatiasJJ** [comment]
Could be a preparation step (I think some lessons have such in  a separate box) that describes:
- you need a github repo. Make a new one or open an existing one.
- you need a jupyter notebook in the repository. Make a new one or use an existing one, (or download that linked there)
- create `requirements.txt` -instructions here rather
- commit and push

then starts the exercise instructions

**Comment by MatiasJJ** [comment]
I have time to do this maybe Tue evening 😬
