### ISSUE TITLE
Motivation page: "How does the Binder instance know which Python packages to load?"

### ISSUE THREAD

**Issue by MatiasJJ** [coderefinery/jupyter#155]
What is the point of this question in here https://coderefinery.github.io/jupyter/motivation/#case-examples

**Comment by bast** [comment]
The goal of that question/exercise is to be able to figure out where Binder stores dependencies for a notebook. It gets them from requirements.txt or environment.yml or other relevant files. This nicely connects with reproducibility lesson.

**Comment by MatiasJJ** [comment]
Oh sure – I see. Aaaand in connects to later stuff about binder then.
It is just not handled there so it felt separate there.

**Comment by bast** [comment]
It is definitely not clear enough :-) Let's add more text/clarification.
