### ISSUE TITLE
List of exercises is bloated

### ISSUE THREAD

**Issue by MatiasJJ** [coderefinery/jupyter#161]
This list https://coderefinery.github.io/jupyter/exercises/ has a lot more stuff than in https://coderefinery.github.io/2023-09-19-workshop/exercises/

**Comment by MatiasJJ** [comment]
This is because there's some automagicks instide the lecture that retrieves everything. Then in workshop page we handpick.

**Comment by bast** [comment]
I think this is then not a problem? Closing.
