### ISSUE TITLE
Focus on the relevant in version control

### ISSUE THREAD

**Issue by MatiasJJ** [coderefinery/jupyter#168]
https://coderefinery.github.io/jupyter/version-control/

Here could be a screenshot illustrating the horror of plain diff – maybe together with a pic of jupyter notebook source code. No need to demostrate live.

Then go straight to demonstrating how nicely things work with CR conda included libraries + mention (maybe demo) nbdime CLI

**Comment by MatiasJJ** [comment]
@bast do you have time to edit this?

**Comment by MatiasJJ** [comment]
This takes then 5min teaching 5min demo

**Comment by bast** [comment]
Yes I will find some time.
