### ISSUE TITLE
follow PEP-8 in all code snippets

### ISSUE THREAD

**Issue by wikfeldt** [coderefinery/jupyter#2]
particularly spaces between variables in function calls

**Comment by bast** [comment]
I normally check this automatically with `pycodestyle` or `yapf` but not sure how to do this in combo with Jupyter notebook.

**Comment by bast** [comment]
I fixed the examples except in the "Exercises" episode which I will anyway skip in my teaching.

**Comment by bast** [comment]
Adjusted also the Gaussian noise example.

**Comment by bast** [comment]
This is done now, except in some exercises which I never have time to visit anyway during a lesson.
