### ISSUE TITLE
Please less magic and directory creation and navigation in example notebooks

### ISSUE THREAD

**Issue by bast** [coderefinery/jupyter#24]
I don't think this is a typical use case. Following the lesson I felt rather confused with all the shell commands and shell escapes. Please let us stick to a typical notebook use-case.

**Comment by bast** [comment]
I would prefer if a notebook I download from the web does not create directories and travels around my directory tree structure so I am not sure we should show this use case.

**Comment by wikfeldt** [comment]
i think analyzing a dataset like the word-count data is a typical use case, but maybe we should include this data in the jupyter repository instead, under `data/`. that would simplify the example a lot

**Comment by bast** [comment]
The analysis is a typical use case but we need to make it more self-contained: Fetch the data from the web, run analysis.

**Comment by wikfeldt** [comment]
solved in #27
