### ISSUE TITLE
Code block inside a markdown cell looks confusing

### ISSUE THREAD

**Issue by bast** [coderefinery/jupyter#25]
In the zipf example the code block looks like a code cell but is code inside a text cell. This tries to connect to the rest of the workshop but it felt artificial to me and does not look like a natural use case for notebook. Also I am not sure non-Python developers get the "aha" effect there with all the Python code that is to be copy-pasted.

**Comment by wikfeldt** [comment]
would it be better if we load code into a cell from a file included with the repo? maybe it's too much code, but on the other hand notebooks usually do contain more code than simple one-liners in separate cells.

**Comment by bast** [comment]
But why is the code not already part of the notebook? Why are we loading/copying it from some place?

**Comment by wikfeldt** [comment]
fixed in #27
