### ISSUE TITLE
convert into jekyll lesson

### ISSUE THREAD

**Issue by wikfeldt** [coderefinery/jupyter#26]
I would like to try converting the material into a conventional Jekyll lesson.
The motivation is:
- other lessons use this, so it'll be easier for all instructors (including those not using nor teaching jupyter) to contribute
- copy-pasting code from lesson material will be easier/more intuitive (and more similar to other lessons) than loading source files into cells or copy-pasting from markdown cells
- more modularity using episodes
- more easily extensible, just add episodes (including optional ones)
- purpose and take-home messages more clearly communicated via episode questions/objectives/keypoints
- lesson can be browsed and learned from even without running jupyter, material more accessible compared to rendering the notebooks on github
- task and challenge boxes from jekyll layout more clearly demarcate exercises, and support clickable solutions

Any comments on this?

**Comment by bast** [comment]
Sounds convincing to me. I could add that with Jekyll format it would be also a bit easier to review changes to the lesson without invoking nbdime.

**Comment by wikfeldt** [comment]
fixed in #27
