### ISSUE TITLE
Is using "Shell commands" good practice?

### ISSUE THREAD

**Issue by bast** [coderefinery/jupyter#48]
In my understanding this creates notebooks with side-effects.

**Comment by bast** [comment]
I am now going through some issues in this repo while preparing for teaching this coming week at a local workshop with chemistry colleagues.

Is it OK if I mention in the material that shell commands are possible and mention that they can introduce non-portable side-effects and at the same time remove explicit examples that we have in the material?

Anybody would prefer if we keep these in the material?

**Comment by wikfeldt** [comment]
i think it's ok to remove explicit examples and replace with mentioning them.

Of course shell commands can create side effects, but the way i think most users use them is as one-offs, i.e. you create a cell, run some shell commands and then remove the cell. Just like one does with terminal while working on code in e.g. text editor, but jupyter enables people to do everything inside the notebook. So i wouldn't say shell commands in notebooks are bad practice,  they come at a risk if misused, but that's the same with many other practices

**Comment by bast** [comment]
Thanks! I agree that it can be useful when prototyping and trying things out. I was in my comment mostly concerned about reproducibility. I will see how I can reword the text to make both perspectives clearer.
