### ISSUE TITLE
Link to http://activityinequality.stanford.edu/

### ISSUE THREAD

**Issue by bast** [coderefinery/jupyter#49]
We used to have that in the material but took it out but it is a nice example where we can also discuss the importance of `requirements.txt`.

**Comment by rkdarst** [comment]
Which episode would you like it in?  My thought is 06-sharing, as a new exercise right after the requirements.txt one.  But could also fit earlier on.

**Comment by bast** [comment]
It can be in the sharing part. When I gave this lesson, I showed it in the motivation since it is a very nice example but I noted that there is tiny problem if you try to reproduce it today and promised that we would try to do better at the end of the lesson and connected to it at the end.

So feel free to mention it where you think it fits best.
