### ISSUE TITLE
Exercise "Playing around with a widget"

### ISSUE THREAD

**Issue by bast** [coderefinery/jupyter#56]
I am experimenting with changing the exercise. I find in the current form it's difficult to "sell"/explain plotting every N-th point.

I find the function fitting more convincing. Alternatively we plot the actual random points and vary N and not only slices.

**Comment by wikfeldt** [comment]
there are probably so many different and more interesting exercises so feel free to change anything!

**Comment by bast** [comment]
Great! I will try to come up with something, of course via code review.
