### ISSUE TITLE
jupyter-widgets installation instructions

### ISSUE THREAD

**Issue by bast** [coderefinery/jupyter#62]
Reported by a helper:

> In the Jupyter-lab installation instructions, this is missing
> `jupyter labextension install @jupyter-widgets/jupyterlab-manager`
> Later in the lesson it is mentioned but somehow, I missed it since it was not in the instructions

**Comment by bast** [comment]
From chat:
> thing is that jupyter labextension install @jupyter-widgets/jupyterlab-manager shouldn't be needed when using the jupyterlab extension manager
> i guess i should experiment with different OSs etc to see how it can fail

**Comment by pmitev** [comment]
Perhaps include the installation of `matplotlib` as well - that was also missing but kind of obvious.

**Comment by rkdarst** [comment]
To make things more fun, it seems that the extension manager might be included by default now:
   https://discourse.jupyter.org/t/extension-manager-now-default-in-jupyterlab-2-1/4057

perhaps that is part of the confusion, too?

**Comment by rkdarst** [comment]
For widgets, it does say to activate it in the installation instructions: "and then activate it by installing the @jupyter-widgets/jupyterlab-manager extension via the extension manager." - this is a different way, using the relatively new extension manager.

And the extension manager confusion above is unrelated: `@jupyter-widgets/jupyterlab-manager` != "extension manager".

**Comment by rkdarst** [comment]
Can someone check if this is fixed in these commits?  I didn't make it auto-close, since I wasn't fully sure if it was correct.

**Comment by pmitev** [comment]
Feels really strange. It did not work at the beginning as before. I was already writing that it does not work... Meanwhile I installed another extension and after that rebuild it just miraculously worked.

**Comment by pmitev** [comment]
OK, tried it again from scratch. Despite it says during the installation that `@jupyter-widgets/jupyterlab-manager` is build it needs manual installation once gitlab-is running - then it works...

**Comment by bast** [comment]
I will check this now again for upcoming workshop and maybe the problem is gone and then I will close it.
