### ISSUE TITLE
01-motivation: second example missing R kernel

### ISSUE THREAD

**Issue by rantahar** [coderefinery/jupyter#66]
In the second example in lesson 01, when opening https://github.com/timalthoff/activityinequality in mybinder, the R kernel is not loaded. According to mybinder documentation (https://mybinder.readthedocs.io/en/latest/using/config_files.html) the repository should have a runtime.txt or a DESCRIPTION for the R kernel to be included.

The simple solution would be to for the repository, fix and add create a pull request. We could use the fork in the meantime But do we want to depend on external repositories keeping up to date?

**Comment by bast** [comment]
I think showing real projects here is good. Also that they have room for improvement. We don't expect them to keep up to date but we can discuss how one could improve them.

I am checking whether I get the same problem ...

**Comment by bast** [comment]
Getting the same problem but I think it's good to have this problem. I am adding a hint/explanation.
