### ISSUE TITLE
Show widgets/plugins only as demo, and give more time to Binder

### ISSUE THREAD

**Issue by bast** [coderefinery/jupyter#67]
We often have trouble installing/enabling these and showing that it exists is in my opinion more useful rather than "requiring" it in exercises and let exercise rooms run into trouble.

Also I find Binder/Zenodo part relevant for everybody and more important than the interact widgets. We often spend 20 minutes on the latter and 5-10 minutes on the former and I suggest to make the Binder/Zenodo part more prominent and a part of a core exercise instead of a quick demo.

**Comment by bast** [comment]
I am strongly convinced that everybody after this workshop should be able to share a notebook via Binder. I think we should give 20-25 minutes for such an exercise.

**Comment by bast** [comment]
Also this connects nicely to the reproducibility lesson.

**Comment by bast** [comment]
Widgets can be demonstrated in Binder where they work out of the box.

**Comment by wikfeldt** [comment]
i totally agree to only demonstrating widgets. It's clear now that they're not worth the debugging hassle. But in addition to the instructor showing how they work, one can mention that participants can try them out in Binder if they want

**Comment by rkdarst** [comment]
I also agree, only demonstrate.  Simplicity overrules everything.

**Comment by bast** [comment]
The material is adapted but this needs to be documented in the instructor guide.
