### ISSUE TITLE
fourth exercise references non-existing "nobel.csv"

### ISSUE THREAD

**Issue by mehimself** [coderefinery/jupyter#68]

**Comment by bast** [comment]
It's here: https://github.com/coderefinery/jupyter/blob/gh-pages/data/nobels.csv. Is some link out of date?

**Comment by bast** [comment]
Is it the link referencing `data/nobels.csv`? I guess it should be `data/nobel.csv`.

**Comment by mehimself** [comment]
I will create a link to it. It was just plain text

**Comment by mehimself** [comment]
I reformulated the last sentence to avoid the impression that the file is an unprovided dependency
